// GENERATED by scripts/generate.mjs - do not hand-edit; run `pnpm --filter @hubbub/games generate`.
// Eager registry for the SERVER and host-desktop; browsers use ./lazy.ts instead. A sibling
// game repo absent on disk is omitted here rather than left as an unresolvable import.
import type { GameRegistry } from "@hubbub/sdk";
import { tttLogic } from "@hubbub/game-tictactoe";
import { utttLogic } from "@hubbub/game-ultimate-tictactoe";
import { tapRaceLogic } from "@hubbub/game-tap-race";
import { musicGuesserLogic } from "@hubbub/game-music-guesser";
import { splitOpinionsLogic } from "@hubbub/game-split-opinions";

export const GAME_LOGICS: GameRegistry = {
  "ttt": tttLogic,
  "uttt": utttLogic,
  "tap-race": tapRaceLogic,
  "music-guesser": musicGuesserLogic,
  "split-opinions": splitOpinionsLogic,
};

export const GAME_IDS = Object.keys(GAME_LOGICS);

export function getLogic(gameId: string | null) {
  return gameId ? GAME_LOGICS[gameId] ?? null : null;
}
