// GENERATED by scripts/generate.mjs - do not hand-edit; run `pnpm --filter @hubbub/games generate`.
// Optional per-game settings SCHEMA, EAGER on the browser path - keep each game's own
// settings-schema.ts an import leaf (enforced by settings-schema-leaf.test.ts). A game with no
// schema, or whose sibling repo is absent on disk, is skipped; this map is intentionally partial.
import type { SettingsSchema } from "@hubbub/sdk";
import { MUSIC_GUESSER_SETTINGS_SCHEMA } from "@hubbub/game-music-guesser/settings";
import { SPLIT_OPINIONS_SETTINGS_SCHEMA } from "@hubbub/game-split-opinions/settings";

export const GAME_SETTINGS_SCHEMAS: Partial<Record<string, SettingsSchema>> = {
  "music-guesser": MUSIC_GUESSER_SETTINGS_SCHEMA,
  "split-opinions": SPLIT_OPINIONS_SETTINGS_SCHEMA,
};

export function getSettingsSchema(gameId: string | null): SettingsSchema | null {
  return gameId ? GAME_SETTINGS_SCHEMAS[gameId] ?? null : null;
}

export type { SettingsSchema, SettingsField, SettingsFieldOption } from "@hubbub/sdk";
